# Generated by Django 5.1.1 on 2024-09-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('price', models.FloatField(verbose_name='Mahsulot narxi')),
                ('date', models.DateField(verbose_name="Qo'shilgan sana")),
                ('description', models.TextField(verbose_name='Mahsulot tavsifi')),
                ('quantity', models.IntegerField(verbose_name='Mahsulot miqdori')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Mahsulot rasmi')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Foydalanuvchi ismi')),
                ('password', models.CharField(max_length=255, verbose_name='Parol')),
                ('rate', models.IntegerField(default=0, verbose_name='Reyting')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Foydalanuvchi rasmi')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'Foydalanuvchi')], max_length=50, verbose_name='Rol')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Daromad nomi')),
                ('quantity', models.BigIntegerField(verbose_name='Miqdor')),
                ('price', models.BigIntegerField(verbose_name='Narx')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Xarajat nomi')),
                ('price', models.BigIntegerField(verbose_name='Narx')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'db_table': 'cost',
            },
        ),
    ]
