# Generated by Django 5.1.1 on 2024-10-23 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_staffdailywork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdailywork',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
