# Generated by Django 5.1.1 on 2024-10-25 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_staffdailywork_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdailywork',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
